// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOM2tledn8yU1AWoBf4zTkiEIQ9e13mbE',
    appId: '1:411466399036:web:1d1a410917bd89adba3239',
    messagingSenderId: '411466399036',
    projectId: 'voice-cal-a63f4',
    authDomain: 'voice-cal-a63f4.firebaseapp.com',
    storageBucket: 'voice-cal-a63f4.firebasestorage.app',
    measurementId: 'G-X6ZVPLWRHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6E3YEWsClhlyTaPxUrTqfqzbLtudA4aI',
    appId: '1:411466399036:android:29839acbf9fd8799ba3239',
    messagingSenderId: '411466399036',
    projectId: 'voice-cal-a63f4',
    storageBucket: 'voice-cal-a63f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc0V0VhF-OoxzHsSJotNrL8lgkPB8XZHw',
    appId: '1:411466399036:ios:a3ea82c9053f9e55ba3239',
    messagingSenderId: '411466399036',
    projectId: 'voice-cal-a63f4',
    storageBucket: 'voice-cal-a63f4.firebasestorage.app',
    iosBundleId: 'com.example.voicecal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc0V0VhF-OoxzHsSJotNrL8lgkPB8XZHw',
    appId: '1:411466399036:ios:a3ea82c9053f9e55ba3239',
    messagingSenderId: '411466399036',
    projectId: 'voice-cal-a63f4',
    storageBucket: 'voice-cal-a63f4.firebasestorage.app',
    iosBundleId: 'com.example.voicecal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOM2tledn8yU1AWoBf4zTkiEIQ9e13mbE',
    appId: '1:411466399036:web:f66bdb26a6945bc8ba3239',
    messagingSenderId: '411466399036',
    projectId: 'voice-cal-a63f4',
    authDomain: 'voice-cal-a63f4.firebaseapp.com',
    storageBucket: 'voice-cal-a63f4.firebasestorage.app',
    measurementId: 'G-HYF7QDPJ4M',
  );
}
